import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Auto-generates sidebar from folder structure.
// Each app folder under docs/ becomes a collapsible category.
// Just add a _category_.json in each folder to control label & position.
const sidebars: SidebarsConfig = {
  wikiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
